version: 2
jobs:
  build:
      working_directory: /node-boilerplate
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: cache verify
            command: npm cache verify
        - run:
            name: module install
            command: npm install
        - run:
            name: test
            command: npm run test:coverage
