version: 2
jobs:
  build:
    working_directory: ~/node-boilerplate
    docker:
      - image: circleci/node:16@sha256:a1ac30bbd231fb1e8efbd52075b9d5918339421989d35997107b44aecbaa78bf
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: module install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
