version: 2
jobs:
  build:
    working_directory: ~/node-boilerplate
    docker:
      - image: circleci/node:16@sha256:1f49bbda3c5f83a2e5381663e914724c1a7b167d5f1a8cade489ab3e05c8ab31
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: module install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
