version: 2
jobs:
  build:
      working_directory: /node-boilerplate
      docker:
        - image: node:6-alpine
      steps:
        - checkout
        - run:
            name: module install
            command: yarn
        - run:
            name: test
            command: npm run test:coverage
